apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ../../base/ai/flowise
  - ../../base/cnpg
  - ../../base/homepage
#  - ../../base/logging
  - ../../base/monitoring
  - ../../base/podinfo
#  - ../../base/ai/open-webui
#  - ../../base/n8n
